excluded:
  - Pods
  
disabled_rules:
  - line_length 
  
function_parameter_count:
  warning: 5
  error: 10

file_length:
   warning: 600
   error: 1000

function_body_length:
  warning: 70
  error: 100

variable_name:
  min_length: 1
  max_length:
    warning: 40
    error: 45
